import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import PointsDistributionProvider from '@/context/PointsDistributionContext';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PointsDistributionProvider>{children}</PointsDistributionProvider>
        <Toaster />
      </body>
    </html>
  );
}
